### ISSUE TITLE
Implement the level UX from the new Web-TouchPanel

### ISSUE THREAD

**Issue by sumnerboy12** [OXRS-IO/OXRS-IO-TouchPanel-ESP32-FW#53]
Instead of the little popup in the top-right of the tile to show the level bar as you change it from the device, make the entire tile a bar whose level changes depending on state.

**Comment by moinmoin-sh** [comment]
Could you live with rounded corners of the bar?
TBH I'm not so happy with this layout. Looks cluttered to my because icons and text are somehow broken when the bar is dividing them.
No clue how to handle the label text to make sure it's hown properly when divided.

Do you have the APP in production (real life examples)?

![grafik](https://user-images.githubusercontent.com/53935853/229367682-3fb81b45-a304-40c7-b589-0fd942c958a3.png)

**Comment by sumnerboy12** [comment]
![image](https://user-images.githubusercontent.com/5060842/229380207-2de82c40-af89-4d93-a111-e24c024db315.png)

**Comment by sumnerboy12** [comment]
![image](https://user-images.githubusercontent.com/5060842/229380243-210d47c4-cb6c-440b-b406-37fe920ad6cd.png)

**Comment by sumnerboy12** [comment]
I think your solution looks great

**Comment by moinmoin-sh** [comment]
Not a solution yet - just a POC to understand what would be possible.

**Comment by sumnerboy12** [comment]
Think this can be closed - what you have done looks great. Just need a release with it included :).
